version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: uis-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: uis_development
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
